name: Deploy
on:
  schedule:
    - cron: '0 1 * * *'
  push:
    branches:
      - 'master'
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'
          stable: true
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Make
        run: make
        working-directory: ${{ github.workspace }}/wireguard-go
      - name: Copy wireguard-go binary into root
        run: mkdir -p ${{ github.workspace }}/root/usr/bin/ && cp ${{ github.workspace }}/wireguard-go/wireguard-go ${{ github.workspace }}/root/usr/bin/wireguard-go
      - name: Extra Vars
        id: extravars
        run: echo ::set-output name=repository_name::${GITHUB_REPOSITORY#*\/}
      - name: DockerHub Registry Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: GitHub Container Registry Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Container Image Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=${{ github.ref == 'refs/heads/master' && 'true' || 'auto' }}
          images: |
            ghcr.io/${{ github.repository }}
            docker.io/blakerandall/${{ steps.extravars.outputs.repository_name }}
      - name: Container Image Publish
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.workspace }}/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
