#!/usr/bin/with-contenv bash

if [ -f /usr/bin/apt ]; then
    apt-get update
fi

INSTALL_PACKAGES=(iproute2 iptables net-tools iputils-ping ifupdown openresolv wireguard-tools)
for PKG in "${INSTALL_PACKAGES[@]}"; do
    echo "Installing ${PKG}"

    # Ubuntu
    if [ -f /usr/bin/apt ]; then
        DEBIAN_FRONTEND="noninteractive"
        apt-get install -y --no-install-recommends ${PKG}
    fi

    # Alpine
    if [ -f /sbin/apk ]; then
        apk add --no-cache ${PKG}
    fi

done

if [ -f /usr/bin/apt ]; then
    rm -rf /var/lib/apt/lists/*
fi
